version: "3.9"

services:
  app:
    build:
      context: .
      target: app
    image: youtube-laravel-demo-app
    container_name: youtube_app
    restart: unless-stopped
    env_file:
      - .env.docker
    environment:
      APP_ENV: ${APP_ENV:-production}
      APP_DEBUG: ${APP_DEBUG:-false}
      APP_URL: ${APP_URL:-http://localhost}
      DB_HOST: db
    volumes:
      - storage:/var/www/html/storage
      - bootstrap_cache:/var/www/html/bootstrap/cache
    depends_on:
      - db

  web:
    build:
      context: .
      target: web
    image: youtube-laravel-demo-web
    container_name: youtube_web
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - "8080:80"
    volumes:
      - storage:/var/www/html/storage
      - bootstrap_cache:/var/www/html/bootstrap/cache

  db:
    image: postgres:16-alpine
    container_name: youtube_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE:-youtube_database}
      POSTGRES_USER: ${DB_USERNAME:-laravel}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secret}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-laravel}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  storage:
  bootstrap_cache:
  postgres_data: